export const STORAGE_KEYS = {
  QUEUE: 'hb_queue',
  JOB_PREFIX: 'hb_job_',
  RESULTS: 'hb_results',
  HEARTBEAT: 'hb_heartbeat',
  SESSION: 'hb_session',
  CONFIG: 'hb_config',
};

export const MESSAGE_TYPES = {
  // Dashboard <-> Bridge
  PING: 'HIGGSBOT_PING',
  PONG: 'HIGGSBOT_PONG',
  QUEUE_SUBMIT: 'HIGGSBOT_QUEUE_SUBMIT',
  QUEUE_CONTROL: 'HIGGSBOT_QUEUE_CONTROL',
  STATE_SYNC: 'HIGGSBOT_STATE_SYNC',

  // Service Worker <-> Content Script
  EXECUTE_GENERATION: 'EXECUTE_GENERATION',
  GENERATION_RESULT: 'GENERATION_RESULT',
  CHECK_SESSION: 'CHECK_SESSION',
  SESSION_STATUS: 'SESSION_STATUS',
};

export const DEFAULTS = {
  POLL_INTERVAL_MS: 3000,
  HEARTBEAT_INTERVAL_MS: 5000,
  DASHBOARD_SYNC_INTERVAL_MS: 2000,
  GENERATION_GAP_MS: 25000,
  GENERATION_JITTER_MS: 8000,
  GENERATION_TIMEOUT_MS: 120000,
  MAX_RETRIES: 3,
  SESSION_CHECK_INTERVAL: 10, // every N jobs
};
